import type { Metadata } from "next";
import { Poppins, Rubik, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
    variable: "--font-pops",
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
})

const rubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
    variable: "--font-jakarta",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Doc Chamber",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} ${rubik.variable} ${jakarta.variable} antialiased`}
            >
                <SessionProvider>
                    <main>
                        {children}
                    </main>
                </SessionProvider>
                <Toaster richColors position="top-center"/>
            </body>
        </html>
    );
}
